# Visualizing UK Climate Change
#### Author: Andras Gelanyi
### Notebook for Preparing temporal data sets for the UK and England, based on MET Office data

In [1]:
import json
import numpy as np
import pandas as pd

In [2]:
tempUK = pd.read_csv('met_data/MET-UK-annual-mean-air-temp.csv')
tempUK.drop(columns=['spr', 'sum', 'aut', 'win'], inplace=True)
tempUK.set_index('year', inplace=True)
tempUK.sort_index(ascending=True, inplace=True)

tempEngland = pd.read_csv('met_data/MET-England-annual-mean-air-temp.csv')
tempEngland.drop(columns=['spr', 'sum', 'aut', 'win'], inplace=True)
tempEngland.set_index('year', inplace=True)
tempEngland.sort_index(ascending=True, inplace=True)

precUK = pd.read_csv('met_data/MET-UK-annual-total-precipitation.csv')
precUK.drop(columns=['spr', 'sum', 'aut', 'win'], inplace=True)
precUK.set_index('year', inplace=True)
precUK.sort_index(ascending=True, inplace=True)

In [3]:
array_years = np.array([])
array_tempUK = np.array([])
array_tempEngland = np.array([])
array_precUK = np.array([])

for year in tempUK.index:
    #print(f'Working on year {year}')
    array_years = np.append(array_years, year)
    array_tempUK = np.append(array_tempUK, tempUK.loc[year].ann)
    array_tempEngland = np.append(array_tempEngland, tempEngland.loc[year].ann)
    array_precUK = np.append(array_precUK, precUK.loc[year].ann)


print(array_years.size)
print(array_tempUK.size)
print(array_tempEngland.size)
print(array_precUK.size)

print(repr(array_years.astype(int)))
print(repr(array_precUK))

# Exporting to a CSV (not used)
#np.savetxt('data/UK-years.csv', array_years.astype(int), delimiter=',')

137
137
137
137
array([1885, 1886, 1887, 1888, 1889, 1890, 1891, 1892, 1893, 1894, 1895,
       1896, 1897, 1898, 1899, 1900, 1901, 1902, 1903, 1904, 1905, 1906,
       1907, 1908, 1909, 1910, 1911, 1912, 1913, 1914, 1915, 1916, 1917,
       1918, 1919, 1920, 1921, 1922, 1923, 1924, 1925, 1926, 1927, 1928,
       1929, 1930, 1931, 1932, 1933, 1934, 1935, 1936, 1937, 1938, 1939,
       1940, 1941, 1942, 1943, 1944, 1945, 1946, 1947, 1948, 1949, 1950,
       1951, 1952, 1953, 1954, 1955, 1956, 1957, 1958, 1959, 1960, 1961,
       1962, 1963, 1964, 1965, 1966, 1967, 1968, 1969, 1970, 1971, 1972,
       1973, 1974, 1975, 1976, 1977, 1978, 1979, 1980, 1981, 1982, 1983,
       1984, 1985, 1986, 1987, 1988, 1989, 1990, 1991, 1992, 1993, 1994,
       1995, 1996, 1997, 1998, 1999, 2000, 2001, 2002, 2003, 2004, 2005,
       2006, 2007, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016,
       2017, 2018, 2019, 2020, 2021])
array([1013.9, 1095. ,  806.5,  994.2,  931.5, 1012.1, 1109.8,  978.4,
        941.1, 1102.7,  961.2,  988.7, 1037.1, 1021.6, 1018.3, 1150.6,
        927.3,  882.3, 1345.9,  963.8,  931.4, 1070.4, 1042.6,  977.4,
       1035.4, 1128.1, 1010.7, 1218.5, 1010.9, 1101.5, 1049.1, 1178.6,
       1021.3, 1112.2, 1015.5, 1127.9,  891.9, 1031.7, 1203.5, 1162.6,
       1057.2, 1083.5, 1198.9, 1240.3, 1048.6, 1167.6, 1106.2, 1086.5,
        831.3, 1062.8, 1134. , 1054.3, 1001.8, 1178.4, 1083.9, 1029.7,
        935.8, 1020.2, 1066.8, 1077.3,  998.5, 1148.1,  974.9, 1193.4,
       1031.4, 1188.2, 1185.6, 1000. ,  937.8, 1295.3,  881.7, 1031. ,
       1089.8, 1118.7,  987.4, 1200.9, 1082. , 1030.9, 1000.9,  918.6,
       1138.8, 1187.8, 1204.2, 1071.9, 1002.4, 1120.5,  935.3,  986.4,
        928.8, 1180.7,  921.4,  974.1, 1103.5, 1062.2, 1171.5, 1155.2,
       1181.7, 1199.1, 1085. , 1090.1, 1102.2, 1213.4, 1060.8, 1160.9,
       1045.1, 1203.7, 1024.7, 1217.4, 1149.7, 1216.5, 1050.3,  935.2,
       1048.7, 1298.4, 1271.8, 1372.5, 1049.3, 1280.3,  900.1, 1208.9,
       1079.7, 1173.2, 1195.7, 1293.2, 1208.1,  945.4, 1162.6, 1329.6,
       1084. , 1292.8, 1265.3, 1096.5, 1118.4, 1053.5, 1232.2, 1333.8,
       1104.2])

In [4]:
print("Temperature (UK)")
print(repr(array_tempUK))
print("Temperature (England)")
print(repr(array_tempEngland))

Temperature (UK)
array([7.36, 7.45, 7.51, 7.28, 8.02, 7.96, 7.6 , 7.02, 8.78, 8.19, 7.55,
       8.26, 8.23, 8.88, 8.57, 8.28, 8.08, 7.73, 8.02, 7.99, 8.19, 8.29,
       7.83, 8.31, 7.52, 8.09, 8.81, 8.17, 8.59, 8.7 , 7.81, 8.11, 7.52,
       8.33, 7.42, 8.45, 9.24, 7.63, 7.97, 8.19, 8.12, 8.59, 8.07, 8.35,
       7.98, 8.29, 7.98, 8.35, 8.82, 8.87, 8.52, 8.26, 8.33, 8.92, 8.57,
       8.01, 7.96, 8.03, 8.88, 8.44, 9.13, 8.35, 8.37, 8.81, 9.34, 8.3 ,
       8.11, 7.99, 8.91, 8.13, 8.23, 7.9 , 8.84, 8.25, 9.24, 8.54, 8.67,
       7.56, 7.4 , 8.31, 7.75, 8.19, 8.47, 8.16, 8.12, 8.31, 8.73, 8.1 ,
       8.43, 8.38, 8.77, 8.74, 8.27, 8.23, 7.59, 8.26, 8.1 , 8.66, 8.83,
       8.57, 7.78, 7.67, 7.99, 8.73, 9.23, 9.38, 8.54, 8.69, 8.33, 8.89,
       9.17, 8.18, 9.41, 9.16, 9.37, 9.1 , 8.8 , 9.44, 9.47, 9.44, 9.42,
       9.7 , 9.56, 9.02, 9.14, 7.94, 9.61, 8.74, 8.74, 9.88, 9.18, 9.29,
       9.53, 9.45, 9.39, 9.62, 9.28])
Temperature (England)
array([ 8.11,  8.25,  7.97,  7.82,  8.5 ,  8.45,  8.1 ,  7.68,  9.44,
        8.82,  8.28,  8.89,  8.97,  9.58,  9.31,  9.09,  8.66,  8.4 ,
        8.79,  8.64,  8.72,  9.02,  8.51,  8.86,  8.17,  8.8 ,  9.63,
        8.95,  9.35,  9.45,  8.54,  8.77,  8.14,  9.09,  8.1 ,  9.15,
       10.08,  8.29,  8.68,  8.86,  8.81,  9.29,  8.77,  9.14,  8.63,
        9.07,  8.58,  8.97,  9.44,  9.57,  9.32,  8.89,  9.11,  9.63,
        9.22,  8.61,  8.62,  8.66,  9.6 ,  9.1 ,  9.82,  9.02,  9.17,
        9.54, 10.1 ,  9.06,  8.87,  8.75,  9.45,  8.81,  8.87,  8.43,
        9.58,  8.97, 10.  ,  9.26,  9.49,  8.1 ,  7.95,  8.94,  8.48,
        9.  ,  9.2 ,  8.89,  8.86,  9.1 ,  9.31,  8.78,  9.18,  9.07,
        9.47,  9.49,  9.01,  8.91,  8.4 ,  8.92,  8.84,  9.44,  9.6 ,
        9.28,  8.52,  8.39,  8.73,  9.42, 10.17, 10.29,  9.2 ,  9.49,
        9.13,  9.84, 10.07,  8.8 , 10.14,  9.97, 10.26,  9.92,  9.63,
       10.28, 10.23, 10.21, 10.16, 10.57, 10.34,  9.8 ,  9.92,  8.76,
       10.54,  9.53,  9.43, 10.75, 10.15, 10.12, 10.39, 10.43, 10.22,
       10.56, 10.06])

In [5]:
print(f"Mean temperature in the UK: {array_tempUK.mean()}")
print("Temperature diff from mean (UK)")
array_tempUK_diff = np.subtract(array_tempUK, array_tempUK.mean()).round(2)
print(repr(array_tempUK_diff))

print(f"Mean temperature in England: {array_tempEngland.mean()}")
print("Temperature diff from mean (England)")
array_tempEngland_diff = np.subtract(array_tempEngland, array_tempEngland.mean()).round(2)
print(repr(array_tempEngland_diff))

Mean temperature in the UK: 8.456715328467155
Temperature diff from mean (UK)
array([-1.1 , -1.01, -0.95, -1.18, -0.44, -0.5 , -0.86, -1.44,  0.32,
       -0.27, -0.91, -0.2 , -0.23,  0.42,  0.11, -0.18, -0.38, -0.73,
       -0.44, -0.47, -0.27, -0.17, -0.63, -0.15, -0.94, -0.37,  0.35,
       -0.29,  0.13,  0.24, -0.65, -0.35, -0.94, -0.13, -1.04, -0.01,
        0.78, -0.83, -0.49, -0.27, -0.34,  0.13, -0.39, -0.11, -0.48,
       -0.17, -0.48, -0.11,  0.36,  0.41,  0.06, -0.2 , -0.13,  0.46,
        0.11, -0.45, -0.5 , -0.43,  0.42, -0.02,  0.67, -0.11, -0.09,
        0.35,  0.88, -0.16, -0.35, -0.47,  0.45, -0.33, -0.23, -0.56,
        0.38, -0.21,  0.78,  0.08,  0.21, -0.9 , -1.06, -0.15, -0.71,
       -0.27,  0.01, -0.3 , -0.34, -0.15,  0.27, -0.36, -0.03, -0.08,
        0.31,  0.28, -0.19, -0.23, -0.87, -0.2 , -0.36,  0.2 ,  0.37,
        0.11, -0.68, -0.79, -0.47,  0.27,  0.77,  0.92,  0.08,  0.23,
       -0.13,  0.43,  0.71, -0.28,  0.95,  0.7 ,  0.91,  0.64,  0.34,
        0.98,  1.01,  0.98,  0.96,  1.24,  1.1 ,  0.56,  0.68, -0.52,
        1.15,  0.28,  0.28,  1.42,  0.72,  0.83,  1.07,  0.99,  0.93,
        1.16,  0.82])
Mean temperature in England: 9.180802919708029
Temperature diff from mean (England)
array([-1.07, -0.93, -1.21, -1.36, -0.68, -0.73, -1.08, -1.5 ,  0.26,
       -0.36, -0.9 , -0.29, -0.21,  0.4 ,  0.13, -0.09, -0.52, -0.78,
       -0.39, -0.54, -0.46, -0.16, -0.67, -0.32, -1.01, -0.38,  0.45,
       -0.23,  0.17,  0.27, -0.64, -0.41, -1.04, -0.09, -1.08, -0.03,
        0.9 , -0.89, -0.5 , -0.32, -0.37,  0.11, -0.41, -0.04, -0.55,
       -0.11, -0.6 , -0.21,  0.26,  0.39,  0.14, -0.29, -0.07,  0.45,
        0.04, -0.57, -0.56, -0.52,  0.42, -0.08,  0.64, -0.16, -0.01,
        0.36,  0.92, -0.12, -0.31, -0.43,  0.27, -0.37, -0.31, -0.75,
        0.4 , -0.21,  0.82,  0.08,  0.31, -1.08, -1.23, -0.24, -0.7 ,
       -0.18,  0.02, -0.29, -0.32, -0.08,  0.13, -0.4 , -0.  , -0.11,
        0.29,  0.31, -0.17, -0.27, -0.78, -0.26, -0.34,  0.26,  0.42,
        0.1 , -0.66, -0.79, -0.45,  0.24,  0.99,  1.11,  0.02,  0.31,
       -0.05,  0.66,  0.89, -0.38,  0.96,  0.79,  1.08,  0.74,  0.45,
        1.1 ,  1.05,  1.03,  0.98,  1.39,  1.16,  0.62,  0.74, -0.42,
        1.36,  0.35,  0.25,  1.57,  0.97,  0.94,  1.21,  1.25,  1.04,
        1.38,  0.88])